/*
 * libxmegaE5_error.h
 *
 * Created: 2022/01/07 4:43:18
 *  Author: kiyot
 */ 


#ifndef LIBXMEGAE5_ERROR_H_
#define LIBXMEGAE5_ERROR_H_

#define LIB_XMEGA_E5_ERROR_OK									(0)
#define LIB_XMEGA_E5_ERROR_NULL									(-1)
#define LIB_XMEGA_E5_ERROR_NODEV								(-2)
#define LIB_XMEGA_E5_ERROR_NOBUF								(-3)
#define LIB_XMEGA_E5_ERROR_INVAL								(-4)
#define LIB_XMEGA_E5_ERROR_NOT_IMPLIMENTED						(-5)
#define LIB_XMEGA_E5_ERROR_BUSY									(-6)

#define LIB_XMEGA_E5_ERROR_TIMER_CANNOT_CONFIGURATE				(-11)

#define LIB_XMEGA_E5_ERROR_UART_INVALID_BAUDRATE				(-12)
#define LIB_XMEGA_E5_ERROR_UART_BUF_FULL						(-13)
#define LIB_XMEGA_E5_ERROR_UART_BUF_EMPTY						(-14)

#define LIB_XMEGA_E5_ERROR_SPI_INVALID_CLK						(-15)
#define LIB_XMEGA_E5_ERROR_SPI_INVALID_TYPE						(-16)
#define LIB_XMEGA_E5_ERROR_SPI_INVALID_MODE						(-17)
#define LIB_XMEGA_E5_ERROR_SPI_INVALID_ORDER					(-18)

#define LIB_XMEGA_E5_ERROR_ADC_UNKNOWN_CAPTURE_MODE				(-19)
#define LIB_XMEGA_E5_ERROR_ADC_INVALID_BIT_RESOLUTION			(-20)
#define LIB_XMEGA_E5_ERROR_ADC_INVALID_SAMPLING_RATE			(-21)
#define LIB_XMEGA_E5_ERROR_ADC_INVALID_CHANNEL					(-22)

#define LIB_XMEGA_E5_ERROR_DAC_INVALID_CHANNEL					(-23)

#define LIB_XMEGA_E5_ERROR_GPIO_PORT_NOTFOUND					(-24)
#define LIB_XMEGA_E5_ERROR_GPIO_PIN_NOTFOUND					(-25)
#define LIB_XMEGA_E5_ERROR_GPIO_INVALID_DIR						(-26)
#define LIB_XMEGA_E5_ERROR_GPIO_INVALID_PIN_MODE				(-27)
#define LIB_XMEGA_E5_ERROR_GPIO_INVALID_INT_MODE				(-28)
#define LIB_XMEGA_E5_ERROR_GPIO_INVALID_CB						(-29)

#define LIB_XMEGA_E5_ERROR_I2C_NACK								(-30)
#define LIB_XMEGA_E5_ERROR_I2C_INVALID_MODE						(-31)
#define LIB_XMEGA_E5_ERROR_I2C_INVALID_CLK						(-32)
#define LIB_XMEGA_E5_ERROR_I2C_BUS_ERROR						(-33)



#endif /* LIBXMEGAE5_ERROR_H_ */