/*
 * gpio_setting.c
 *
 * Created: 2021/12/30 10:59:30
 *  Author: kiyot
 */
#include <stdint.h>
#include <stddef.h>

#include <samd51_gpio.h>

#include "lib4legs.h"

void initialize_gpio(void)
{
	//J USB
	samd51_gpio_configure(USB_DM_PIN,   SAMD51_GPIO_INOUT, SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_FUNC_H);
	samd51_gpio_configure(USB_DP_PIN,   SAMD51_GPIO_INOUT, SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_FUNC_H);

	//J Power
	samd51_gpio_configure(VCC_EN_PIN,      SAMD51_GPIO_OUT, SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(SW_SENS_PIN,     SAMD51_GPIO_IN,  SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(POWER_ON_PIN,    SAMD51_GPIO_OUT, SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(EN_7V4_PIN,      SAMD51_GPIO_OUT, SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(EN_6V0_PIN,      SAMD51_GPIO_OUT, SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(DCDC_PG_PIN,     SAMD51_GPIO_IN,  SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(VREF_PIN,        SAMD51_GPIO_IN, SAMD51_GPIO_NO_PULL, SAMD51_GPIO_MUX_FUNC_B);
	samd51_gpio_configure(VBAT_SENS_A_PIN, SAMD51_GPIO_IN, SAMD51_GPIO_NO_PULL, SAMD51_GPIO_MUX_FUNC_B);
	samd51_gpio_configure(VCC_SENS_A_PIN,  SAMD51_GPIO_IN, SAMD51_GPIO_NO_PULL, SAMD51_GPIO_MUX_FUNC_B);

	//J LED
	samd51_gpio_configure(LED0_PIN, SAMD51_GPIO_OUT, SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_output(LED0_PIN, 1);

	//J IMU
	samd51_gpio_configure(BP_S_PIN,  SAMD51_GPIO_OUT,   SAMD51_GPIO_PULLUP_DOWN, SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(SCL_S_PIN, SAMD51_GPIO_INOUT, SAMD51_GPIO_NO_PULL,     SAMD51_GPIO_MUX_FUNC_C);
	samd51_gpio_configure(SDA_S_PIN, SAMD51_GPIO_INOUT, SAMD51_GPIO_NO_PULL,     SAMD51_GPIO_MUX_FUNC_C);
	
	//J Legs
	samd51_gpio_configure(INT0_PIN, SAMD51_GPIO_INOUT, SAMD51_GPIO_PULLUP_DOWN,   SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(INT1_PIN, SAMD51_GPIO_OUT, SAMD51_GPIO_PULLUP_DOWN,   SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(INT2_PIN, SAMD51_GPIO_OUT, SAMD51_GPIO_PULLUP_DOWN,   SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(INT3_PIN, SAMD51_GPIO_OUT, SAMD51_GPIO_PULLUP_DOWN,   SAMD51_GPIO_MUX_DEFAULT);
	samd51_gpio_configure(SCL_PIN,  SAMD51_GPIO_INOUT, SAMD51_GPIO_NO_PULL, SAMD51_GPIO_MUX_FUNC_C);
	samd51_gpio_configure(SDA_PIN,  SAMD51_GPIO_INOUT, SAMD51_GPIO_NO_PULL, SAMD51_GPIO_MUX_FUNC_C);

	return;
}
